services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CrudEtudiant
    # ports:
    #   - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -proot
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s

  springboot-app:
    image: khaledkbc/crud-etudiant:latest
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/CrudEtudiant?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: on-failure

volumes:
  mysql_data:

