global:
  scrape_interval: 10s

scrape_configs:

  - job_name: 'springboot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['testpipeline-springboot-app-1:8089']




